#!/usr/bin/env bash

path="/home/ubuntu/onekgenomes/"

# Remove VCF files
rm ${path}data/variantCalls/*

# Run Python main file with nohup (check nohup.out for output)
nohup python3 ${path}src/dataAcq/aux/main.py ${path} &

#python3 ${path}src/dataAcq/aux/main.py ${path}
