#!/usr/bin/env bash

# Path to project directory.
path="/home/ubuntu/onekgenomes/"

# Clear VCF and error files.
rm ${path}data/variantCalls/* ${path}data/sparseMats/* ${path}err/* 2>/dev/null

# Run main.py.
#nohup python3 ${path}src/dataAcq/aux/main.py ${path} &

python3 ${path}src/dataAcq/aux/main.py ${path}
